# Generated by Django 3.0 on 2019-12-11 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_pedido_criado_em'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=140)),
                ('email', models.EmailField(max_length=254)),
                ('data_nascimento', models.DateTimeField()),
                ('senha', models.CharField(max_length=32)),
                ('confirmacao_senha', models.CharField(max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
